name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改
id = "f8f7ca2ba9cb4360b8772196221ee925"				#KV数据库id
